Msg.Web/Areas/mobile/Controllers/MeController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Glimpse.Core.Extensions;
using Microsoft.Practices.Unity;
using Msg.Bll;
using Msg.Bll.Helpers;
using Msg.Entities;
using Msg.Tools;
using Msg.Tools.Logging;
using Msg.Utils;
using Msg.Web.App_Start;

namespace Msg.Web.Areas.Mobile.Controllers
{
    public class MeController : Controller
    {
        private readonly OrdersHelper _ordersHelper = UnityConfig.GetConfiguredContainer().Resolve<OrdersHelper>();
        private readonly UsersHelper _usersHelper = UnityConfig.GetConfiguredContainer().Resolve<UsersHelper>();
        private readonly CouponsHelper _couponsHelper = UnityConfig.GetConfiguredContainer().Resolve<CouponsHelper>();
        private readonly SchoolHelper _schoolHelper = UnityConfig.GetConfiguredContainer().Resolve<SchoolHelper>();

        #region 首页

        public ActionResult Index()
        {
            if (UserAuth.IsAuthenticated)
            {
                //订单数量
                ViewBag.orderCount = _ordersHelper.GetOrderCountByUid(UserAuth.UserId);
            }
            return View();
        }

        #endregion

        #region 我的订单

        //我的订单
        [MobileAuthFilters]
        public ActionResult MyOrders()
        {
            var total = 0;
            ViewBag.MenuMyOrdersClassOver = "over";
            //默认未支付的订单
            var unReceivedOrders = _ordersHelper.GetUserOrdersByStatus(UserAuth.UserId, null, 1, 10, out total);
            ViewBag.NoNeedTopAdvert = true;
            return View(unReceivedOrders);
        }

        [MobileAuthFilters]
        public PartialViewResult _MyOrders(int page, int? orderStatus)
        {
            var total = 0;

            IQueryable<OrdersEntity> orders;

            switch (orderStatus)
            {
                case (int)OrderStatusEnum.UnPay:
                    orders = _ordersHelper.GetUserOrdersByStatus(UserAuth.UserId, OrderStatusEnum.UnPay, page, 10,
                        out total);
                    break;
                case (int)OrderStatusEnum.Sended:
                    orders = _ordersHelper.GetUserOrdersByStatus(UserAuth.UserId, OrderStatusEnum.Sended, page, 10,
                        out total);
                    break;
                case (int)OrderStatusEnum.Done:
                    orders = _ordersHelper.GetUserOrdersByStatus(UserAuth.UserId, OrderStatusEnum.Done, page, 10,
                        out total);
                    break;
                default:
                    orders = _ordersHelper.GetUserOrdersByStatus(UserAuth.UserId, null, page, 10, out total);
                    break;
            }
            ViewBag.Pager = PagerHelper.CreatePagerByAjax(page, 10, total, "myOrders.loadOrders");
            return PartialView(orders);
        }

        //取消多个订单
        [MobileAuthFilters]
        public JsonResult CancelOrders(string ids)
        {
            OperationResult result = null;
            if (!string.IsNullOrEmpty(ids))
            {
                if (ids.Contains(","))
                {
                    var arrIds = ids.Split(',');
                    foreach (string id in arrIds)
                    {
                        result = _ordersHelper.ModifyOrderStatus(id, OrderStatusEnum.Cancel, UserAuth.UserId);
                    }
                }
            }
            else
            {
                result = _ordersHelper.ModifyOrderStatus(ids, OrderStatusEnum.Cancel, UserAuth.UserId);
            }
            return ReturnHelper.Instance.GetJsonResult(result);
        }

        #endregion

        #region 我的优惠券

        [MobileAuthFilters]
        public ActionResult MyCoupons(int page = 1)
        {
            var total = 0;
            var data = _couponsHelper.GetMyCouponsEntities(UserAuth.UserId, page, 10, out total);
            return View(data);
        }

        [MobileAuthFilters]
        public PartialViewResult _MyCoupons(int page = 1)
        {
            var total = 0;
            var data = _couponsHelper.GetMyCouponsEntities(UserAuth.UserId, page, 10, out total);
            return PartialView(data);
        }

        #endregion

        #region 收货地址管理

        //收货地址管理
        [MobileAuthFilters]
        public ActionResult MyAddresses()
        {
            var data = _usersHelper.GetUserAddressEntities(UserAuth.UserId);
            ViewBag.Schools = _schoolHelper.GetUseableSchoolsInCache(UserAuth.UserRegionId);
            ViewBag.Regions = _schoolHelper.GetUseableRegionInCache();
            return View(data);
        }

        //添加、修改收货地址 id:收货地址id
        [MobileAuthFilters]
        public ActionResult EditAddress(string p, int id = 0, int couponId = 0)
        {
            ViewBag.p = p;
            ViewBag.couponId = couponId;
            ViewBag.id = id;
            UserAddressEntity userAddress = null;
            if (id > 0)
            {
                userAddress = _usersHelper.GetUserAddressEntity(id);
            }
            if (userAddress == null)
            {
                userAddress = new UserAddressEntity { RegionId = UserAuth.UserRegionId, SchoolId = UserAuth.SchoolId };
            }

            var regionId = userAddress.RegionId;
            var schoolId = userAddress.SchoolId;
            if (Session["regionId"] != null)
            {
                try
                {
                    regionId = int.Parse(Session["regionId"].ToString());
                }
                catch (System.Exception)
                {
                }
            }
            if (Session["schoolId"] != null)
            {
                try
                {
                    schoolId = int.Parse(Session["schoolId"].ToString());
                }
                catch (System.Exception)
                {
                }
            }
            var list = _schoolHelper.GetUseableRegionInCache();
            var defaultRegion = regionId > 1 ? list.FirstOrDefault(r => r.Id == regionId) : list.FirstOrDefault();
            var regionName = "";
            if (defaultRegion == null)
            {
                regionId = 1;
                regionName = "重庆市";
            }
            else
            {
                regionId = defaultRegion.Id;
                regionName = defaultRegion.Name;
            }
            ViewBag.regionId = regionId;
            ViewBag.regionName = regionName;
            if (regionId > 0 && schoolId > 0)
            {
                ViewBag.schoolId = schoolId;
                var school = _schoolHelper.GetUseableSchoolsInCache(regionId).FirstOrDefault(r => r.Id == schoolId);
                if (school != null)
                {
                    ViewBag.schoolName = school.Name;
                }
            }

            return View(userAddress);
        }

        #endregion

    }
}

Msg.Web/Controllers/AlipayController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Web.Mvc;
using Com.Alipay;
using Microsoft.Practices.Unity;
using Msg.Bll.Helpers;
using Msg.Entities;
using Msg.Tools;
using Msg.Tools.Extensions;
using Msg.Tools.Logging;
using Msg.Web.App_Start;

namespace Msg.Web.Controllers
{
    public class AlipayController : Controller
    {

        private readonly OrdersHelper _ordersHelper = UnityConfig.GetConfiguredContainer().Resolve<OrdersHelper>();
        private readonly GoodsHelper _goodsHelper = UnityConfig.GetConfiguredContainer().Resolve<GoodsHelper>();

        /// <summary>
        /// 服务器异步通知页面
        /// </summary>
        /// <returns></returns>
        public ActionResult notify_url()
        {
            SortedDictionary<string, string> sPara = GetRequestPost();
            if (sPara.Count > 0)//判断是否有带返回参数
            {
                var aliNotify = new Notify();
                var verifyResult = aliNotify.Verify(sPara, Request.Form["notify_id"], Request.Form["sign"]);

                if (verifyResult)//验证成功
                {
                    try
                    {
                        /////////////////////////////////////////////////////////////////////////////////////////////////////////////
                        //请在这里加上商户的业务逻辑程序代码
                        //——请根据您的业务逻辑来编写程序（以下代码仅作参考）——
                        //获取支付宝的通知返回参数，可参考技术文档中服务器异步通知参数列表
                        string trade_no = Request.Form["trade_no"];         //支付宝交易号
                        string order_no = Request.Form["out_trade_no"];     //获取订单号
                        string total_fee = Request.Form["total_fee"];       //获取总金额
                        string subject = Request.Form["subject"];           //商品名称、订单名称
                        string body = Request.Form["body"];                 //商品描述、订单备注、描述
                        string buyer_email = Request.Form["buyer_email"];   //买家支付宝账号
                        string trade_status = Request.Form["trade_status"]; //交易状态
                        string refund_status = Request.Form["refund_status"];//退款状态

                        var order = _ordersHelper.GetOrdersEntityByOrderNo(order_no);
                        if (order != null)
                        {
                            if (!string.IsNullOrEmpty(trade_status))
                            {
                                #region 交易处理

                                if (trade_status == "TRADE_SUCCESS")
                                {
                                    #region 处理订单状态  已付款 -> 正在出库

                                    //该判断示买家已在支付宝交易管理中产生了交易记录且付款成功，但卖家没有发货

                                    //判断该笔订单是否在商户网站中已经做过处理
                                    //如果没有做过处理，根据订单号（out_trade_no）在商户网站的订单系统中查到该笔订单的详细，并执行商户的业务程序
                                    //如果有做过处理，不执行商户的业务程序

                                    //修改订单状态
                                    var result = _ordersHelper.ModifyOrderStatus(order.Id.ToString(),
                                        OrderStatusEnum.Outputing,
                                        order.User.Id);

                                    if (result.ResultType.Equals(OperationResultType.Success))
                                    {
                                        //修改商品售卖数量
                                        _goodsHelper.ModifyGoodsSoldCount(order.Items);


                                        Response.Write("success");  //请不要修改或删除
                                    }

                                    #endregion


                                }

                                //添加交易日志
                                AddTradeLog(order.User.Id, order.User.NickName, total_fee, order.Id.ToString(),
                                    trade_no, buyer_email, trade_status);

                                #endregion

                                if (!string.IsNullOrEmpty(refund_status))
                                {
                                    #region 退款处理  暂不支持

                                    //switch (refund_status)
                                    //{
                                    //    case "WAIT_SELLER_AGREE"://等待卖家同意退款
                                    //        #region 处理订单状态  申请退款

                                    //        #endregion
                                    //        break;
                                    //    case "WAIT_BUYER_RETURN_GOODS"://等待卖家退货
                                    //        #region WAIT_BUYER_RETURN_GOODS

                                    //        #endregion
                                    //        break;
                                    //    case "WAIT_SELLER_CONFIRM_GOODS"://买家已退货，等待卖家收到退货
                                    //        #region WAIT_SELLER_CONFIRM_GOODS



                                    //        #endregion
                                    //        break;
                                    //    case "REFUND_SUCCESS"://卖家同意退款，退款成功，交易结束
                                    //        #region 处理订单状态  退款成功

                                    //        #endregion
                                    //        break;
                                    //    case "SELLER_REFUSE_BUYER"://卖家拒绝退款
                                    //        #region 处理订单状态   驳回退款申请


                                    //        #endregion
                                    //        break;
                                    //}
                                    //Response.Write("success");  //请不要修改或删除

                                    #endregion
                                }
                            }
                        }

                        //——请根据您的业务逻辑来编写程序（以上代码仅作参考）——


                        /////////////////////////////////////////////////////////////////////////////////////////////////////////////
                    }
                    catch (Exception ex)
                    {
                        LogHelper.WriteException("支付宝异步支付回调异常 ---> ", ex);
                    }

                }
                else//验证失败
                {
                    Response.Write("fail");
                }
            }
            else
            {
                Response.Write("无通知参数");
            }

            return new EmptyResult();
        }

        /// <summary>
        /// 页面跳转同步通知页面
        /// </summary>
        /// <returns></returns>
        public ActionResult return_url()
        {
            var sPara = GetRequestGet();

            if (sPara.Count > 0)//判断是否有带返回参数
            {
                var aliNotify = new Notify();
                var verifyResult = aliNotify.Verify(sPara, Request.QueryString["notify_id"], Request.QueryString["sign"]);

                if (verifyResult)//验证成功
                {
                    try
                    {
                        /////////////////////////////////////////////////////////////////////////////////////////////////////////////
                        //请在这里加上商户的业务逻辑程序代码

                        //——请根据您的业务逻辑来编写程序（以下代码仅作参考）——
                        //获取支付宝的通知返回参数，可参考技术文档中页面跳转同步通知参数列表
                        var trade_no = Request.QueryString["trade_no"]; //支付宝交易号
                        var order_no = Request.QueryString["out_trade_no"]; //获取订单号
                        var type = Request.QueryString["type"]; //获取类别，0：web支付，1：app支付
                        var total_fee = Request.QueryString["total_fee"]; //获取总金额
                        var subject = Request.QueryString["subject"]; //商品名称、订单名称
                        var body = Request.QueryString["body"]; //商品描述、订单备注、描述
                        var buyer_email = Request.QueryString["buyer_email"]; //买家支付宝账号
                        var trade_status = Request.QueryString["trade_status"]; //交易状态

                        var order = _ordersHelper.GetOrdersEntityByOrderNo(order_no);
                        if (order != null)
                        {

                            if (trade_status == "TRADE_SUCCESS")
                            {
                                #region 处理订单状态  已付款 -> 正在出库
                                //该判断示买家已在支付宝交易管理中产生了交易记录且付款成功，但卖家没有发货

                                //判断该笔订单是否在商户网站中已经做过处理
                                //如果没有做过处理，根据订单号（out_trade_no）在商户网站的订单系统中查到该笔订单的详细，并执行商户的业务程序
                                //如果有做过处理，不执行商户的业务程序

                                //修改订单状态
                                var result = _ordersHelper.ModifyOrderStatus(order.Id.ToString(), OrderStatusEnum.Outputing,
                                 order.User.Id);

                                if (result.ResultType.Equals(OperationResultType.Success))
                                {
                                    //修改商品售卖数量
                                    _goodsHelper.ModifyGoodsSoldCount(order.Items);

                                    //添加交易日志
                                    AddTradeLog(order.User.Id, order.User.NickName, total_fee, order.Id.ToString(), trade_no, buyer_email, trade_status);

                                    return RedirectToAction("PayOk", new { orderNo = order.OrderNo });

                                }

                                #endregion


                            }
                            else
                            {
                                //添加交易日志
                                AddTradeLog(order.User.Id, order.User.NickName, total_fee, order.Id.ToString(), trade_no, buyer_email, trade_status);
                                Response.Write("trade_status=" + Request.QueryString["trade_status"]);
                            }




                        }

                        //打印页面
                        Response.Write("验证成功<br />");

                        //——请根据您的业务逻辑来编写程序（以上代码仅作参考）——

Msg.Web/Views/Me/GoodsUp.cshtml
@using Msg.Entities
@model Msg.Entities.GoodsEntity

@{
    ViewBag.Title = Model.Id > 0 ? "编辑商品" : "上架商品";
    Layout = "~/Views/Shared/_UCenterLayout.cshtml";
    var product = ViewBag.Product as ProductsEntity ?? new ProductsEntity();
}
@section head{
    <link href="@Url.Content("~/Content/ueditor/themes/default/ueditor.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/My97DatePicker/skin/WdatePicker.css")" rel="stylesheet" />
}

<div class="per_right per_order">
    <div class="order_h">
        <div class="h_left">@(Model.Id > 0 ? "编辑商品" : "上架商品")</div>
    </div>
    <div class="entre_f">
        <form id="fr_publish" method="POST" action="@Url.Action("GoodsUp", "Me")">
            @Html.AntiForgeryToken()
            <input type="hidden" value="@product.Id" name="productId" />
            @Html.HiddenFor(f => f.Id)
            <table cellpadding="0" cellspacing="0" width="100%">
                <tbody>
                    <tr>
                        <td width="140" align="right">产品名称：</td>
                        <td>
                            @Html.TextBoxFor(f => f.Product.Name, new { disabled = "disabled" })
                        </td>
                    </tr>
                    <tr>
                        <td width="140" align="right">短标题：</td>
                        <td>
                            @Html.TextBoxFor(f => f.ShortTitle, new { maxlength = "200", placeholder = "请输入短标题，200字以内" })
                        </td>
                    </tr>
                    <tr>
                        <td width="140" align="right">长标题：</td>
                        <td>
                            @Html.TextBoxFor(f => f.LongTitle, new { maxlength = "500", placeholder = "请输入长标题，200字以内" })
                        </td>
                    </tr>

                    <tr>
                        <td width="140" align="right">售价：</td>
                        <td>
                            @Html.TextBoxFor(f => f.SellPrice, new { maxlength = 10 })
                        </td>
                    </tr>
                    <tr>
                        <td width="140" align="right">支付方式：</td>
                        <td>
                            <label class="checkbox-inline">
                                <input type="checkbox" id="cbx_cashOnline" checked="checked">线上支付
                                @Html.CheckBoxFor(f => f.IsCashOnline)
                            </label>
                            <label class="checkbox-inline">
                                <input type="checkbox" id="cbx_cashDelivery">货到付款
                                @Html.CheckBoxFor(f => f.IsCashDelivery)
                            </label>
                        </td>
                    </tr>
                    <tr>
                        <td width="120" align="right">是否特卖：</td>
                        <td>
                            <label class="radio-inline">
                                <input type="radio" name="IsSaleOption" onchange=" saleRadioChangeEvent(); " id="rd_IsSale_true">是
                                @Html.CheckBoxFor(f => f.IsSale)
                            </label>
                            <label class="radio-inline">
                                <input type="radio" name="IsSaleOption" id="rd_IsSale_false" checked="checked">否
                            </label>
                        </td>
                    </tr>
                    <tr class="tr_saleTime" style="display: none">
                        <td width="120" align="right">开始时间：</td>
                        <td>
                            <input type="text" id="txt_startTime" name="SaleStartTime" class="Wdate" onclick=" WdatePicker({ dateFmt: 'yyyy-MM-dd', maxDate: '#F{$dp.$D(\'txt_endTime\')||\'2020-10-01\'}', alwaysUseStartDate: true, onpicked: clearFiltDate }) ">
                        </td>
                    </tr>
                    <tr class="tr_saleTime" style="display: none">
                        <td align="right" valign="top">结束时间：</td>
                        <td>
                            <input type="text" id="txt_endTime" name="SaleEndTime" class=" Wdate" onclick=" WdatePicker({ dateFmt: 'yyyy-MM-dd', maxDate: '2020-10-01', onpicked: clearFiltDate }) ">
                        </td>
                    </tr>

                    <tr>
                        <td align="right">编辑产品详细信息：</td>
                        <td>
                            <div id="txt_Desc"></div>
                            @Html.HiddenFor(f => f.Desc)
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td class="cl_ff3300">
                            上传商品时，默认同意美速购各项条款，最终解释权归美速购所有！
                            @if (ViewBag.ErrMsg is string && !string.IsNullOrEmpty(ViewBag.ErrMsg))
                            {
                                <br><br>
                                <span style="font-weight: bold">@ViewBag.ErrMsg</span>
                            }
                        </td>
                    </tr>
                    <tr>
                        <td><button type="reset" class="btn btn-default" onclick="javascript:$('form').reset();">重置</button></td>
                        <td class="per_button">
                            <button type="button" id="btn_submit" class="btn btn-default">提交</button>

                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
    </div>
</div>

@section Scripts{
    <script src="@Url.Content("~/Content/My97DatePicker/WdatePicker.js")"></script>
    <script type="text/javascript">
        var detailOption = {
            //这里可以选择自己需要的工具按钮名称,此处仅选择如下
            toolbars: [['Undo', 'Redo', 'Source', '|', 'Bold', 'Italic', 'Underline', '|', 'ForeColor', 'BackColor', 'FontFamily', 'FontSize', '|', 'InsertTable', 'DeleteTable', 'InsertParagraphBeforeTable', 'InsertRow', 'DeleteRow', 'InsertCol', 'DeleteCol', 'MergeCells', 'MergeRight', 'MergeDown', 'SplittoCells', 'SplittoRows', 'SplittoCols', '|', 'Link', 'Unlink', '|', 'InsertImage', 'Emotion', 'InsertVideo', 'Map', '|', 'wordimage', 'Preview']],
            initialContent: '@Html.Raw(Model.Desc)',
            autoHeightEnabled: true //是否自动长高
        };
        ue_edit_detail = new baidu.editor.ui.Editor(detailOption);
        ue_edit_detail.render('txt_Desc');

        $(function () {

            //提交按钮
            $("#btn_submit").bind("click", function () {
                var shortTitle = $("#ShortTitle").val();
                var longTitle = $("#LongTitle").val();
                var sellPrice = $("#SellPrice").val();
                var isSale = $("#rd_IsSale_true").is(":checked");
                var saleStartTime = $("#txt_startTime").val();
                var saleEndTime = $("#txt_endTime").val();
                if (isEmpty(shortTitle)) {
                    MsgDialog.Alert(false, "请填写短标题！");
                    return;
                }
                if (isEmpty(longTitle)) {
                    MsgDialog.Alert(false, "请填写长标题！");
                    return;
                }
                if (isEmpty(sellPrice) || isNaN(sellPrice)) {
                    MsgDialog.Alert(false, "价格填写错误！");
                    return;
                }
                if (isSale) {
                    if (isEmpty(saleEndTime) || isEmpty(saleStartTime)) {
                        MsgDialog.Alert(false, "请选择特卖开始/结束时间！");
                        return;
                    }
                }

                $("#IsSale").val(isSale);
                $("#IsCashOnline").val($("#cbx_cashOnline").is(":checked"));
                $("#IsCashDelivery").val($("#cbx_cashDelivery").is(":checked"));
                $("#Desc").val(ue_edit_detail.getContent());

                $("form").submit();
            });

        });

        function saleRadioChangeEvent() {
            var isSale = $("#rd_IsSale_true").is(":checked");
            if (isSale) {
                $(".tr_saleTime").show();
            } else {
                $(".tr_saleTime").hide();
            }
        }

    </script>

}

Msg.Web/Views/Me/ModifyAvatar.cshtml
@{
    ViewBag.Title = "修改头像";
    Layout = "~/Views/Shared/_UCenterLayout.cshtml";
}

@section head
{

}

<div class="per_right">
    <div id="images"></div>
</div>

@section scripts{

    <script src="@Url.Content("~/Scripts/jquery.swfobject.1-1-1.min.js")"></script>
    <script src="@Url.Content("~/Scripts/upload_avatar.js")"></script>

    <script type="text/javascript">
        $(function() {
            up = new SEXY_upload_one_file('up', {
                id: 'images',
                swf_src: '@Url.Content("~/Content/upload_head.swf")',
                save_url: '@Url.Action("AvatarUpload")',
                debug: function(str) {
                    //$('#debug').append(str + '<br>');
                },
                error: function(error) {
                    //$('#error').append(error + '<br>');
                },
                start: function() {
                    //$('#debug').append('上传开始<br>');
                    $(".per_right").showLoading();
                },
                complete: function(backstr) {
                    $(".per_right").hideLoading();
                    backstr = eval('(' + backstr + ')');
                    MsgDialog.Alert(backstr.s, backstr.msg, function () {
                        if (backstr.s) {
                            window.location.href = '@Url.Action("Index")';
                        }
                    });

                }
            });

        })
    </script>
}

Msg.Web/Views/Me/_MyOrders.cshtml
@using Msg.Entities
@using Msg.Tools.Extensions
@using Msg.Utils
@model System.Linq.IQueryable<Msg.Entities.OrdersEntity>

@{
    decimal orderPrice = 0;
}

@if (Model != null && Model.Any())
{
    <table cellpadding="0" cellspacing="0" width="100%">
        <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <th colspan="4">
                        <span class="cl_0093dd">@(item.StatusDesc)</span>&nbsp;&nbsp;
                        订单号：<a href="">@item.OrderNo</a><span class="span1">|</span>
                        @item.Address.ReciverName<span class="span1">|</span>
                        @item.CreateTime.ToZhTime()
                    </th>
                </tr>

                <tr>
                    <td class="td1">
                        <ul>
                            @foreach (var orderItems in item.Items)
                            {
                                <li class="clearfix">
                                    <div class="li1">
                                        <a href="@Url.Action("Details", "Home", new {id = orderItems.Goods.Id})"><img src="@ImagesHelper.GetImgWidthHeight(orderItems.Goods.Product.MainLogo, 80, 80, false)" width="80" height="80"></a>
                                    </div>
                                    <div class="li2">
                                        <a href="@Url.Action("Details", "Home", new {id = orderItems.Goods.Id})">@(orderItems.Goods.ShortTitle)&nbsp;&nbsp; X@(orderItems.Quantity)</a>
                                        <br>@(orderItems.SinglePrice)元
                                    </div>
                                </li>
                            }
                        </ul>
                    </td>
                    <td width="120">@(item.DisplayPrice)元<br>@item.PayWay</td>
                    <td width="120"><a href="@Url.Action("MyOrder", "Me", new {no = item.OrderNo})" target="_blank">订单详情</a></td>
                    @switch (item.Status)
                    {
                        case (int)OrderStatusEnum.UnPay:
                            <td width="170" class="per_button">
                                @if (item.PayWay.Equals(PayWayEnum.CashOnline.ToDescription()))
                                {
                                       <a href="@Url.Action("Payment", "Alipay", new { orderNo = item.OrderNo })" target="_blank">立即付款</a>
                                }
                                <a href="JavaScript:;" onclick="myOrders.cancelOrder('@item.Id');return false; ">取消订单</a>
                            </td>
                                break;
                        case (int)OrderStatusEnum.Sended:
                        <td width="170" class="per_button"><a href="JavaScript:;" onclick="myOrders.confirmReceipt('@item.Id')">确认收货</a></td>
                                break;
                        case (int)OrderStatusEnum.Payed:
                        case (int)OrderStatusEnum.Outputing:
                        case (int)OrderStatusEnum.Received:
                        case (int)OrderStatusEnum.Done:
                        case (int)OrderStatusEnum.Cancel:
                        case (int)OrderStatusEnum.Expired:
                        <td width="170" class="per_button"><a href="@Url.Action("Details", "Home", new {id = item.Items.FirstOrDefault().Goods.Id})">再次购买</a></td>
                                break;
                    }

                </tr>

            }

        </tbody>
    </table>
    @Html.Raw(ViewBag.Pager)
}
else
{
    <div class="dd_list_w">暂无此类型订单，<a href="/" target="_blank">赶快去挑选喜欢的商品吧！</a></div>
}

Msg.Web/Views/Me/_UnPayOrders.cshtml
@using Msg.Utils
@model System.Linq.IQueryable<Msg.Entities.OrdersEntity>

@if (Model.Any())
{
    <table cellpadding="0" cellspacing="0" width="100%" class="dd_list_tab">

        @foreach (var order in Model)
        {
            <tr>
                <td class="clearfix">
                    @foreach (var item in order.Items)
                    {
                        <div class="td1">
                            <a href="@Url.Action("Details", "Home", new { id = item.Goods.Id })"><img src="@ImagesHelper.GetImgWidthHeight(item.Goods.Product.MainLogo, 50, 50, false)" width="50" height="50"></a>
                        </div>
                    }
                </td>
                <td width="40">&times;&nbsp;@order.Items.Sum(f=>f.Quantity)</td>
                <td width="210">订单号：@order.OrderNo</td>
                <td width="110">
                    ￥@(order.DisplayPrice)
                    <br>@order.PayWay
                </td>
                <td width="120"><a href="@Url.Action("MyOrder", new {no = order.OrderNo})" target="_blank">订单详情</a></td>
                <td width="150" class="per_button">
                    <a href="@Url.Action("Payment", "Alipay", new {order = order.OrderNo})">立即付款</a>
                </td>
            </tr>
        }
    </table>
    @Html.Raw(ViewBag.Pager)
}
else
{
    <div class="dd_list_w">还没有未支付的订单，<a href="/" target="_blank">赶快去挑选喜欢的商品吧！</a></div>
}