Msg.Web/Areas/Admin/Controllers/AdManageController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using System.Xml;
using Glimpse.Core.Tab.Assist;
using Msg.Web.App_Start;
using Msg.Web.Areas.Admin.Models;

namespace Msg.Web.Areas.Admin.Controllers
{
    public class AdManageController : Controller
    {
        //
        // GET: /Admin/AdManage/


        // 广告首页
        // GET: /admin/admanage/
        [AdminAuthFilter]
        public ActionResult AdManage()
        {
            string path = Server.MapPath("~/AdScript"); //"F:/Vsworkspace/Projects/Meisugou/Msg.Web/AdScript";
            var filesNameArr = Directory.GetFiles(path, "*.xml");
            var pathArr = new string[filesNameArr.Count<string>()];
            for (int i = 0; i < pathArr.Length; i++)
            {
                // var stringArr = filesNameArr[i].Split('\\');
                pathArr[i] = filesNameArr[i]; //stringArr[stringArr.Length - 1];
            }
            //var pathArr = new string[] { "~/AdScript/index_top.xml", "~/AdScript/index_slide.xml", "~/AdScript/index_buttom.xml" };

            var slidsList = new List<Slide>();

            for (int i = 0; i < pathArr.Length; i++)
            {
                ReadXmlbyFilePath(pathArr[i], ref slidsList);
            }

            // slidsList.OrderBy<Slide,>();
            //var slides = Models.Slide.GetRoot().SubSlides;
            //var idObj = slides.OrderBy(o => o.Id).LastOrDefault();
            //var id = idObj != null ? idObj.Id : 0;

            slidsList = slidsList.OrderBy(s => s.FileName).ThenBy(s => s.OrderNo).ToList();
            return View(slidsList);
        }



        /// <summary>
        /// 从XML文件中读取广告内容
        /// </summary>
        /// <param name="path">xml文件路径物理路径</param>
        /// <param name="slidsList">返回的广告ModelList</param>
        private void ReadXmlbyFilePath(string path, ref List<Slide> slidsList)
        {
            //物理路径
            var serverpath = path;
            //相对路径
            //var serverpath = Server.MapPath(path);
            try
            {
                var xml = new XmlDocument();
                xml.Load(serverpath);
                var root = xml.SelectSingleNode("Root");
                // var AdItems = xml.Value;
                if (root == null) throw new Exception("数据文件错误");
                root = root.SelectSingleNode("AdItems");
                if (root == null) throw new Exception("数据文件错误");



                var sublides = root.ChildNodes;
                for (int i = 0; i < sublides.Count; i++)
                {
                    var sModel = new Slide();
                    sModel.AdSiteName = "";
                    var xmlAttributeCollection = sublides[i].Attributes;
                    if (xmlAttributeCollection != null)
                    {
                        //sModel.Id = int.Parse(xmlAttributeCollection["Id"].Value);

                        sModel.Image = xmlAttributeCollection["Image"].Value;    //图片路径
                        sModel.Title = xmlAttributeCollection["Title"].Value;   //标题
                        sModel.OrderNo = Convert.ToInt32(xmlAttributeCollection["OrderNo"].Value); //排序号
                        sModel.Url = xmlAttributeCollection["Url"].Value;  //链接地址
                        sModel.AdSiteName = xmlAttributeCollection["AdSiteName"].Value;  //广告位置
                        sModel.Remark = xmlAttributeCollection["Remark"].Value;  //备注
                        sModel.FileName = serverpath.Split('\\')[serverpath.Split('\\').Length - 1].Split('.')[0];


                    }
                    slidsList.Add(sModel);
                }
            }
            catch
            {
            }
        }



        /// <summary>
        /// 修改广告图片或者内容(非幻灯片)
        /// </summary>
        /// <param name="model">model</param>
        /// <returns></returns>
        public JsonResult Msg_ModifyImage(Slide model)
        {
            var result = Json(new {isError = false}, JsonRequestBehavior.AllowGet);
            try
            {
                var serverpath = Server.MapPath("~/AdScript/" + model.FileName + ".xml");
                var xml = new XmlDocument();
                xml.Load(serverpath);
                var root = xml.SelectSingleNode("Root");
                if (root == null) throw new Exception("数据文件错误");
                //root = root.SelectSingleNode("AdItems");
                //if (root == null) throw new Exception("数据文件错误");


                root.RemoveAll();
                var element = xml.CreateElement("AdItems");
                var elementModel = xml.CreateElement("Item");
                elementModel.SetAttribute("Title", model.Title);
                //if (!string.IsNullOrEmpty(model.Url) && model.Url.Length > 7 && model.Url.Substring(0,6) == "http://")
                //{
                    elementModel.SetAttribute("Url", model.Url);
                //}
                //else
                //{
                //    result = Json(new { isError = true, msg = "请按照  http://  格式输入连接地址" }, JsonRequestBehavior.AllowGet);
                //    return null;
                //}
                
                elementModel.SetAttribute("Image", model.Image);
                elementModel.SetAttribute("Remark", model.Remark);
                elementModel.SetAttribute("OrderNo", model.OrderNo.ToString());
                elementModel.SetAttribute("AdSiteName", model.AdSiteName);
                elementModel.SetAttribute("FileName", model.FileName);
                element.AppendChild(elementModel);
                root.AppendChild(element);
                xml.AppendChild(root);
                xml.Save(serverpath);

                //缺少删除文件



                //var xmlColletion = root.ChildNodes;
                //for (var i = 0;i<xmlColletion.Count;i++)
                //{
                //    var xmlAttributeCollection = xmlColletion[i].Attributes;
                //    if (xmlAttributeCollection != null)
                //    {
                //        xmlAttributeCollection["Title"].InnerXml = model.Title;
                //    }
                //}


                //<Item Id="1" Title="首页底部通栏广告" OrderNo="0"   Url="http://www.9yjob.com" Image="~/Content/images/logo.png" Remark="首页顶部"   AdSiteName="首页顶部" />

                return result;
            }
            catch (Exception ex)
            {
                return   Json(new { isError = true, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }


        }




        /// <summary>
        /// 修改幻灯片内容
        /// </summary>
        /// <param name="model"> model</param>
        /// <returns></returns>
        public JsonResult Msg_ModifySlide(Slide model, int oldOrderNo)
        {
            try
            {
                var serverpath = Server.MapPath("~/AdScript/" + model.FileName + ".xml");
                var xml = new XmlDocument();
                xml.Load(serverpath);
                var root = xml.SelectSingleNode("Root");
                if (root == null) throw new Exception("数据文件错误");
                root = root.SelectSingleNode("AdItems");
                if (root == null) throw new Exception("数据文件错误");



                var sublides = root.ChildNodes;
                if (model.OrderNo == oldOrderNo)
                {
                    for (var i = 0; i < sublides.Count; i++)
                    {
                        var xmlElementAttrbuteCollections = sublides[i].Attributes;
                        //var xmlAttrbuteCollections = 
                        if (xmlElementAttrbuteCollections != null && xmlElementAttrbuteCollections["OrderNo"].Value == oldOrderNo.ToString())
                        {
                            xmlElementAttrbuteCollections["OrderNo"].InnerXml = model.OrderNo.ToString();
                            //var element = sublides[i];
                            if (xmlElementAttrbuteCollections["OrderNo"].Value != null) xmlElementAttrbuteCollections["OrderNo"].InnerXml = model.OrderNo.ToString();
                            if (xmlElementAttrbuteCollections["Title"].Value != null) xmlElementAttrbuteCollections["Title"].InnerXml = model.Title;

                            if (xmlElementAttrbuteCollections["Url"].Value != null)  xmlElementAttrbuteCollections["Url"].InnerXml = model.Url;
                            //{
                            //    if (string.IsNullOrEmpty(model.Url)&&model.Url.Length > 7 && model.Url.Substring(0, 6) == "http://")
                            //    {

                                  
                                //}
                                //else
                                //{
                                //    return Json(new { isError = true, msg = "请按照  http://  格式输入连接地址" },
                                //        JsonRequestBehavior.AllowGet);
                                //}
                            //}
                            if (xmlElementAttrbuteCollections["Image"].Value != null) xmlElementAttrbuteCollections["Image"].InnerXml = model.Image;
                            if (xmlElementAttrbuteCollections["Remark"].Value != null) xmlElementAttrbuteCollections["Remark"].InnerXml = model.Remark;
                            if (xmlElementAttrbuteCollections["AdSiteName"].Value != null) xmlElementAttrbuteCollections["AdSiteName"].InnerXml = model.AdSiteName;
                        }
                    }
                }
                else
                {
                    for (var i = 0; i < sublides.Count; i++)
                    {
                        var xmlElement = sublides[i].Attributes;
                        if (xmlElement != null)
                        {
                            if (xmlElement["OrderNo"].Value != null && xmlElement["OrderNo"].Value == oldOrderNo.ToString())
                            {
                                xmlElement["OrderNo"].InnerXml = model.OrderNo.ToString();

Msg.Web/Controllers/CommonController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Practices.Unity;
using Msg.Bll.Helpers;
using Msg.FileUpload;
using Msg.Tools.Logging;
using Msg.Web.App_Start;

namespace Msg.Web.Controllers
{
    public class CommonController : Controller
    {
        //
        // GET: /Common/

        /// <summary>
        /// 接收图片
        /// </summary>
        /// <returns></returns>
        public JsonResult RecivePhoto()
        {
            string msg = "";
            //原图地址
            string filesSrc = "";

            var status = false;
            try
            {
                byte[] jpgContent = Request.BinaryRead(Request.ContentLength);
                if (jpgContent != null)
                {
                    HttpPostedFileBase hpFile = HttpContext.Request.Files[0];
                    if (hpFile != null && hpFile.ContentLength > 0)
                    {
                        //返回消息
                        var originalMsg = NewFileUploadHelper.UploadFile(hpFile);

                        if (originalMsg.Status)
                        {
                            filesSrc = originalMsg.FileSrc;
                            status = true; msg = "上传成功";
                        }
                    }
                }
                else
                {
                    msg = "无上传内容";
                }
            }
            catch (Exception ex)
            {
                LogHelper.WriteException("上传图片异常", ex);

                msg = "可能由于网络原因，照片上传失败，请重试！";
                return Json(new { status = false, msg = msg }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { status, msg, filesSrc }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Gets the school by region.
        /// </summary>
        /// <param name="regionId">The region identifier.</param>
        /// <returns></returns>
        public JsonResult GetSchoolByRegion(int regionId)
        {
            var schoolHelper = UnityConfig.GetConfiguredContainer().Resolve<SchoolHelper>();
            var school = schoolHelper.GetUseableSchoolsInCache(regionId).Select(f => new { f.Id, f.RegionId, f.Name });

            return Json(school, JsonRequestBehavior.AllowGet);
        }
    }
}

Msg.Web/Areas/Admin/Views/AdManage/AdManage.cshtml
@{
    ViewBag.Title = "广告管理";
    ViewBag.InnerTopTitle = "广告管理";
}
@using Msg.Utils
@model List<Msg.Web.Areas.Admin.Models.Slide>

<div class="col-lg-6" style="width: 100%">
    <div class="panel panel-default">
        <div class="panel-heading" style="height: 50px;">
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>广告位置</th>
                            <th>广告描述（标题）</th>
                            <th>是否为幻灯片</th>
                            <th>排序号</th>
                            @*  <th>图片路径</th>*@
                            <th>链接地址</th>
                            <th>备注</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null && Model.Any())
                        {

                            foreach (var item in Model)
                            {
  
                                
                            <tr>
                                <td><span id="AdSiteName_@item.FileName-@item.OrderNo">@item.AdSiteName</span></td>

                                <td>
                                    <input value="@item.Title"  id="_Title_@item.FileName-@item.OrderNo" class="ToEdit" onblur="HideInput('Title_@item.FileName-@item.OrderNo')"  />
                                    <span id="Title_@item.FileName-@item.OrderNo" onclick="ShowInput('Title_@item.FileName-@item.OrderNo')">@item.Title</span> </td>

                                @if (@item.OrderNo != 0)
                                {
                                    <td><span>是</span></td>                                  
                                    <td>
                                        <input id="_OrderNo_@item.FileName-@item.OrderNo" value="@item.OrderNo" class="ToEdit" onblur="HideInput('OrderNo_@item.FileName-@item.OrderNo')" />
                                        <span id="OrderNo_@item.FileName-@item.OrderNo" onclick="ShowInput('OrderNo_@item.FileName-@item.OrderNo')">@item.OrderNo</span>
                                    </td>
                                }
                                else
                                {
                                    <td><span>否</span></td>
                                    
                                    <td><span id="OrderNo_@item.FileName-@item.OrderNo" >@item.OrderNo</span>

                                    </td>
 
                                }



                                @*  <td><span>@item.Image</span></td>*@


                                <td>
                                    <input class="ToEdit" value="@item.Url" id="_Url_@item.FileName-@item.OrderNo" onblur="HideInput('Url_@item.FileName-@item.OrderNo')" />
                                    <span id="Url_@item.FileName-@item.OrderNo" onclick="ShowInput('Url_@item.FileName-@item.OrderNo')" >@item.Url</span>
                                </td>



                                <td>
                                    <input value="@item.Remark" id="_Remark_@item.FileName-@item.OrderNo" class="ToEdit" onblur="HideInput('Remark_@item.FileName-@item.OrderNo')" />
                                    <span id="Remark_@item.FileName-@item.OrderNo" onclick="ShowInput('Remark_@item.FileName-@item.OrderNo')">@item.Remark</span>
                                </td>

                                <td>
                                    @if (item.OrderNo != 0)
                                    {
                                        <a href="javascript:;" onclick="EditSlide('@item.FileName','@item.OrderNo'); return false;">修改&nbsp;</a>
                                        <a href="javascript:;" onclick="AddSlide('@item.FileName','@item.OrderNo')">新增&nbsp;</a>
                                        <a href="javascript:;" onclick="DelSilde('@item.FileName','@item.OrderNo')">删除</a>
                                    }
                                    else
                                    {
                                        <a href="javascript:;" onclick="EditImage('@item.FileName'); return false;">修改</a>
                                    }

                                </td>
                            </tr>
                            <tr>
                                <td colspan="6">
                                    <a id="Imgtar_@item.FileName-@item.OrderNo" target="_blank" href="@item.Image">
                                        <img src="@ImagesHelper.GetImgWidthHeight(item.Image, 300, 180, false)" width="300" height="180"  id="Image__@item.FileName-@item.OrderNo"></a><td>
                                                                                                                                                                                          <a href="javascript:;"onclick="change('@item.FileName-@item.OrderNo')" >上传图片</a></td>
                                    <input type="hidden" id="Image_@item.FileName-@item.OrderNo"  value="@item.Image" />
                                </td>
                            </tr>
                            }
                        }
                    </tbody>
                </table>


                @*<div style="float: right">@Html.Raw(ViewBag.Pager)</div>*@
                <!--/.pager-->
            </div>

            <!-- /.table-responsive -->
        </div>
        <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
</div>



<script src="@Url.Content("~/Scripts/jquery.swfobject.1-1-1.min.js")"></script>
<script src="@Url.Content("~/Scripts/sexy_upload_one.js")"></script>



<script type="text/javascript">
    var filenameForImgUrl = "";
    $(function () {
        $(".ToEdit").hide();
    });
    function change(filename) {
        var html = '<div><div class="form-group"><div><a href="javascript:;" id="btn_upload">上传Logo</a></div></div>';
        BootstrapDialog.show({
            title: "上传图片",
            message: $(html),
            closable: true,
            onshown: function (diaglog) {
                up = new SEXY_upload_one_file('up', {
                    id: 'btn_upload',
                    swf_src: '@Url.Content("~/Content/upload_one_file.swf")',
                    btn_src: '@Url.Content("~/Content/images/up_button.png")',
                    up_url: '@Url.Action("RecivePhoto", "Common", new { area = "" })',
                    loading: 'true',
                    btn_w: 131,
                    btn_h: 40,
                    complete: function (backstr) {
                        
                        backstr = eval('(' + backstr + ')');
                        if (backstr.status) {
                            $("#Imgtar_" + filename).attr("href", backstr.filesSrc);
                            $("#Image__" + filename).attr("src", backstr.filesSrc);
                            $("#Image_" + filename).val(backstr.filesSrc);
                        } else {

                            MsgDialog.Alert(false, "失败");
                        }
                        diaglog.close();
                    }
                });
            }
        });

    }









    function ShowInput(elename) {
        $("#_" + elename).show();
        $("#_" + elename).focus();
        $("#" + elename).hide();
    }


    function HideInput(elename) {
        var text = $("#_" + elename).val();
        if (text != "") $("#" + elename).text(text);
        else {
            $("#_" + elename).val($("#"+elename).text());
        }
        $("#" + elename).show();
        $("#_" + elename).hide();

    }

    //编辑单张广告
    function EditImage(fileName) {
        //alert(2111);
        var title = $('#Title_' + fileName + "-0").text();
        var url = $('#Url_' + fileName + "-0").text();
        var image = $('#Image_' + fileName + "-0").val();
        var orderNo = $('#OrderNo_' + fileName + "-0").text();
        var adsitename = $('#AdSiteName_' + fileName + "-0").text();
        var remark = $('#Remark_' + fileName + "-0").text();

        //var filename = fileName;


        if (url == "" || url.length <= 7 || url.substring(0, 7) != "http://") {
            MsgDialog.Alert(false, "请按照  http://  格式输入连接地址");
            return;
        }
        if (isNaN(orderNo)) {
            MsgDialog.Alert(false, "请输正确的排序号！");
            return;
        }
        if (remark == "") {
            MsgDialog.Alert(false, "请填入备注！");
            return;
        }
        if (title == "") {
            MsgDialog.Alert(false, "请填入广告描述（标题）！");
            return;
        }

        var model = {
            title: title,
            url: url,
            orderNo: orderNo,
            image: image,
            adsitename: adsitename,
            remark: remark,
            filename: fileName
        };
        // alert("OK2   ");
        $.get("@Url.Action("Msg_ModifyImage", "AdManage", new { area = "Admin" })?t=" + Math.random(), model, function (result) {
            //alert("ok3");
            //alert(result.isError);
            if (!result.isError) {
                MsgDialog.Alert(true, "修改成功!", function () {
                    location.href = location.href;
                });

            } else {
                MsgDialog.Alert(false, result.msg);

            }
        });
    }

    //编辑幻灯片
    function EditSlide(filename, oldOrderNo) {
        var title = $('#Title_' + filename + "-" + oldOrderNo).text();
        var url = $('#Url_' + filename + "-" + oldOrderNo).text();
        var image = $('#Image_' + filename + "-" + oldOrderNo).val();
        var orderNo = $('#OrderNo_' + filename + "-" + oldOrderNo).text();
        var adsitename = $('#AdSiteName_' + filename + "-" + oldOrderNo).text();
        var remark = $('#Remark_' + filename + "-" + oldOrderNo).text();



        if (url == "" || url.length <= 7 || url.substring(0, 7) != "http://") {
            MsgDialog.Alert(false, "请按照  http://  格式输入连接地址");
            return;
        }
        if (isNaN(orderNo)) {
            MsgDialog.Alert(false, "请输正确的排序号！");
            return;
        }
        if (remark == "") {
            MsgDialog.Alert(false, "请填入备注！");
            return;
        }
        if (title == "") {
            MsgDialog.Alert(false, "请填入广告描述（标题）！");
            return;
        }




        var model = {
            title: title,
            url: url,
            orderNo: orderNo,
            image: image,
            adsitename: adsitename,
            remark: remark,
            filename: filename,
            oldOrderNo: oldOrderNo
        };
        // alert("OK2   ");
        $.get("@Url.Action("Msg_ModifySlide", "AdManage", new { area = "Admin" })?t=" + Math.random(), model, function (result) {
            //alert("ok3");
            //alert(result.isError);
            if (!result.isError) {
                MsgDialog.Alert(true, "修改成功!", function () {
                    location.href = location.href;
                });

            } else {
                MsgDialog.Alert(false, result.msg);

            }
        });

    }

    //新增一张幻灯片
    function AddSlide(filename, oldOrderNo) {
        var title = $('#Title_' + filename + "-" + oldOrderNo).text();
        var url = $('#Url_' + filename + "-" + oldOrderNo).text();
        var image = $('#Image_' + filename + "-" + oldOrderNo).val();
        var orderNo = $('#OrderNo_' + filename + "-" + oldOrderNo).text();
        var adsitename = $('#AdSiteName_' + filename + "-" + oldOrderNo).text();
        var remark = $('#Remark_' + filename + "-" + oldOrderNo).text();


        var model = {
            title: title,
            url: url,
            orderNo: orderNo,
            image: image,
            adsitename: adsitename,
            remark: remark,
            filename: filename
        };
        // alert("OK2   ");
        $.get("@Url.Action("Msg_AddSlide", "AdManage", new { area = "Admin" })?t=" + Math.random(), model, function (result) {
            //alert("ok3");
            //alert(result.isError);
            if (!result.isError) {
                MsgDialog.Alert(true, "修改成功!", function () {
                    location.href = location.href;
                });

            } else {
                MsgDialog.Alert(false, result.msg);

            }
        });
    }



    //删除一张幻灯片
    function DelSilde(filename, oldOrderNo) {
        var title = $('#Title_' + filename + "-" + oldOrderNo).text();
        var url = $('#Url_' + filename + "-" + oldOrderNo).text();
        var image = $('#Image_' + filename + "-" + oldOrderNo).val();
        var orderNo = $('#OrderNo_' + filename + "-" + oldOrderNo).text();
        var adsitename = $('#AdSiteName_' + filename + "-" + oldOrderNo).text();
        var remark = $('#Remark_' + filename + "-" + oldOrderNo).text();


        var model = {
            title: title,
            url: url,
            orderNo: orderNo,
            image: image,
            adsitename: adsitename,
            remark: remark,
            filename: filename
        };
        // alert("OK2   ");
        $.get("@Url.Action("Msg_DelSlide", "AdManage", new { area = "Admin" })?t=" + Math.random(), model, function (result) {
            //alert("ok3");
            //alert(result.isError);
            if (!result.isError) {
                MsgDialog.Alert(true, "修改成功!", function () {
                    location.href = location.href;
                });

            } else if (result.msg == "Last") {
                MsgDialog.Alert(false, "最后一张，请勿删除", function () {
                    location.href = location.href;
                });
            } else {
                MsgDialog.Alert(false, result.msg);
            }
        });
    }


</script>