Msg.Web/Controllers/ExchangesController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Microsoft.Practices.Unity;
using Msg.Bll.Helpers;
using Msg.Bll.Models;
using Msg.Utils;
using Msg.Web.App_Start;

namespace Msg.Web.Controllers
{
    //积分兑换
    public class ExchangesController : Controller
    {
        private readonly GoodsHelper _goodsHelper = UnityConfig.GetConfiguredContainer().Resolve<GoodsHelper>();
        private readonly CommentsHelper _commentsHelper = UnityConfig.GetConfiguredContainer().Resolve<CommentsHelper>();
        private readonly UsersHelper _usersHelper = UnityConfig.GetConfiguredContainer().Resolve<UsersHelper>();
        private readonly ExchangesHelper _exchangesHelper = UnityConfig.GetConfiguredContainer().Resolve<ExchangesHelper>();

        //
        // GET: /Exchanges/

        public ActionResult Index()
        {
            var total = 0;
            var data = _goodsHelper.GetCreditGoods(0, 1000, 1, 30, out total);
            ViewBag.Pager = PagerHelper.CreatePagerByAjax(1, 30, total, "loadCreditGoods");
            ViewBag.NoNeedBanner = true; ViewBag.NoNeedTopAdvert = true;
            return View(data);
        }

        public PartialViewResult _Index(int tabId, int page = 1)
        {
            var total = 0;
            List<CreditGoodsLiteModel> data;
            switch (tabId)
            {
                case 1:
                    data = _goodsHelper.GetCreditGoods(0, 1000, page, 30, out total);
                    break;
                case 2:
                    data = _goodsHelper.GetCreditGoods(1001, 3000, page, 30, out total);
                    break;
                case 3:
                    data = _goodsHelper.GetCreditGoods(3001, 5000, page, 30, out total);
                    break;
                case 4:
                    data = _goodsHelper.GetCreditGoods(5001, 8000, page, 30, out total);
                    break;
                default:
                    data = _goodsHelper.GetCreditGoods(8000, 9999999, page, 30, out total);
                    break;
            }
            ViewBag.Pager = PagerHelper.CreatePagerByAjax(1, 30, total, "loadCreditGoods");
            return PartialView(data);
        }

        //积分兑换商品详情
        public ActionResult Item(int id, int page = 1)
        {
            var total = 0;
            var model = _goodsHelper.GetCreditGoods(id);
            ViewBag.Comments = _commentsHelper.GetCreditGoodsCommentsEntities(id, page, 10, out total);
            ViewBag.HotSelling = _goodsHelper.GetHotSellingGoodsEntities(5, 1);
            ViewBag.ViewHistory = _goodsHelper.GetGoodsViewHistory(5);
            ViewBag.Pager = PagerHelper.CreatePagerByUrl(page, 10, total, "");
            ViewBag.PageNum = page;
            ViewBag.NoNeedTopAdvert = true;
            ViewBag.NoNeedBanner = true;
            return View(model);
        }

        //我的地址
        [AuthFilters]
        public PartialViewResult _MyAddress()
        {
            var data = _usersHelper.GetUserAddressEntities(UserAuth.UserId);
            return PartialView(data);
        }

        //处理兑换
        [AuthFilters]
        public JsonResult ToExchange(int goodsId, int quantiy, int addressId)
        {
            var result = _exchangesHelper.ExchangeGoods(UserAuth.UserId, goodsId, quantiy, addressId);
            return ReturnHelper.Instance.GetJsonResult(result);
        }



    }
}

Msg.Web/Controllers/MeController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Glimpse.Core.Extensions;
using Microsoft.Practices.Unity;
using Msg.Bll;
using Msg.Bll.Helpers;
using Msg.Entities;
using Msg.Tools;
using Msg.Tools.Logging;
using Msg.Utils;
using Msg.Web.App_Start;

namespace Msg.Web.Controllers
{
    [AuthFilters]
    public class MeController : Controller
    {
        private readonly OrdersHelper _ordersHelper = UnityConfig.GetConfiguredContainer().Resolve<OrdersHelper>();
        private readonly CartHelper _cartHelper = UnityConfig.GetConfiguredContainer().Resolve<CartHelper>();
        private readonly ProductsHelper _productsHelper = UnityConfig.GetConfiguredContainer().Resolve<ProductsHelper>();
        private readonly UsersHelper _usersHelper = UnityConfig.GetConfiguredContainer().Resolve<UsersHelper>();
        private readonly GoodsHelper _goodsHelper = UnityConfig.GetConfiguredContainer().Resolve<GoodsHelper>();
        private readonly SuppliersHelper _suppliersHelper = UnityConfig.GetConfiguredContainer().Resolve<SuppliersHelper>();
        private readonly ExchangesHelper _exchangesHelper = UnityConfig.GetConfiguredContainer().Resolve<ExchangesHelper>();
        private readonly CommentsHelper _commentsHelper = UnityConfig.GetConfiguredContainer().Resolve<CommentsHelper>();
        private readonly NotifiesHelper _notifiesHelper = UnityConfig.GetConfiguredContainer().Resolve<NotifiesHelper>();
        private readonly CouponsHelper _couponsHelper = UnityConfig.GetConfiguredContainer().Resolve<CouponsHelper>();
        private readonly SchoolHelper _schoolHelper = UnityConfig.GetConfiguredContainer().Resolve<SchoolHelper>();
        //
        // GET: /Me/

        #region 首页

        public ActionResult Index()
        {
            var totalUnPay = 0;
            var totalUnReceived = 0;
            ViewBag.UnPayOrders = _ordersHelper.GetUserOrdersByStatus(UserAuth.UserId, OrderStatusEnum.UnPay, 1, 10,
                out totalUnPay);
            ViewBag.UnReceivedOrders = _ordersHelper.GetUserOrdersByStatus(UserAuth.UserId, OrderStatusEnum.Sended, 1,
                10, out totalUnReceived);
            ViewBag.UnPayOrdersPager = PagerHelper.CreatePagerByAjax(1, 10, totalUnPay, "index.loadUnPayOrders");
            ViewBag.UnReceivedOrdersPager = PagerHelper.CreatePagerByAjax(1, 10, totalUnReceived,
                "index.loadUnReceivedOrders");
            ViewBag.Carts = _cartHelper.GetCartModels();
            ViewBag.NoNeedTopAdvert = true;
            ViewBag.MenuIndexClassOver = "over";
            return View();
        }

        public PartialViewResult _UnPayOrders(int page = 1)
        {
            var totalUnPay = 0;
            var unPayOrders = _ordersHelper.GetUserOrdersByStatus(UserAuth.UserId, OrderStatusEnum.UnPay, 1, 10,
                out totalUnPay);
            ViewBag.UnPayOrdersPager = PagerHelper.CreatePagerByAjax(1, 10, totalUnPay, "index.loadUnPayOrders");
            return PartialView(unPayOrders);
        }


        public PartialViewResult _UnReceivedOrders(int page = 1)
        {
            var totalUnReceived = 0;
            var unReceivedOrders = _ordersHelper.GetUserOrdersByStatus(UserAuth.UserId, OrderStatusEnum.Sended, 1,
                10, out totalUnReceived);
            ViewBag.UnReceivedOrdersPager = PagerHelper.CreatePagerByAjax(1, 10, totalUnReceived,
                "index.loadUnReceivedOrders");
            return PartialView(unReceivedOrders);
        }


        public ActionResult ModifyAvatar()
        {
            ViewBag.NoNeedTopAdvert = true;
            return View();
        }


        /// <summary>
        /// 上传头像
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [AllowAnonymous]
        public ActionResult AvatarUpload()
        {
            byte[] jpgContent = Request.BinaryRead(Request.ContentLength);
            bool s = true;
            try
            {
                if (jpgContent.Length > 0)
                {
                    var avatar = FileUpload.UploadHelper.SetAvatar(UserAuth.UserId, jpgContent);
                    s = _usersHelper.ModifyAvatar(UserAuth.UserId, avatar);
                }

            }
            catch (Exception ex)
            {
                LogHelper.WriteException("上传头像失败，出现异常", ex);
                s = false;
            }
            return Json(new { s = s, msg = s ? "上传成功" : "上传失败" }, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region 我的订单

        //我的订单
        public ActionResult MyOrders()
        {
            var total = 0;
            ViewBag.MenuMyOrdersClassOver = "over";
            //默认未支付的订单
            var unReceivedOrders = _ordersHelper.GetUserOrdersByStatus(UserAuth.UserId, OrderStatusEnum.UnPay, 1,
                10, out total);
            ViewBag.NoNeedTopAdvert = true;
            return View(unReceivedOrders);
        }


        public PartialViewResult _MyOrders(int page, int? orderStatus)
        {
            var total = 0;

            IQueryable<OrdersEntity> orders;

            switch (orderStatus)
            {
                case (int)OrderStatusEnum.UnPay:
                    orders = _ordersHelper.GetUserOrdersByStatus(UserAuth.UserId, OrderStatusEnum.UnPay, page, 10,
                        out total);
                    break;
                case (int)OrderStatusEnum.Sended:
                    orders = _ordersHelper.GetUserOrdersByStatus(UserAuth.UserId, OrderStatusEnum.Sended, page, 10,
                        out total);
                    break;
                case (int)OrderStatusEnum.Done:
                    orders = _ordersHelper.GetUserOrdersByStatus(UserAuth.UserId, OrderStatusEnum.Done, page, 10,
                        out total);
                    break;
                default:
                    orders = _ordersHelper.GetUserOrdersByStatus(UserAuth.UserId, null, page, 10, out total);
                    break;
            }
            ViewBag.Pager = PagerHelper.CreatePagerByAjax(page, 10, total, "myOrders.loadOrders");
            return PartialView(orders);
        }

        //我的订单详情
        public ActionResult MyOrder(string no)
        {
            ViewBag.MenuMyOrdersClassOver = "over";
            var result = _ordersHelper.GetMyOrderEntity(no, UserAuth.UserId);
            if (result.ResultType.Equals(OperationResultType.Success))
            {
                ViewBag.NoNeedTopAdvert = true;
                return View((OrdersEntity)result.AppendData);
            }
            ViewBag.Errmsg = result.ResultType.ToDescription() + result.Message;
            ViewBag.NoNeedTopAdvert = true;
            return View((OrdersEntity)result.AppendData);
        }

        //取消订单
        public JsonResult CancelOrder(string id)
        {
            var result = _ordersHelper.ModifyOrderStatus(id, OrderStatusEnum.Cancel, UserAuth.UserId);
            return ReturnHelper.Instance.GetJsonResult(result);
        }

        //确认收货
        public JsonResult ConfirmReceipt(string id)
        {
            var result = _ordersHelper.ModifyOrderStatus(id, OrderStatusEnum.Received, UserAuth.UserId);
            return ReturnHelper.Instance.GetJsonResult(result);
        }


        #endregion

        #region 我的创业集市

        public ActionResult MyMarket(int page=1)
        {
            var total = 0;
            var data = _productsHelper.GetApplyEntities(UserAuth.UserId, page, 10, out total);
            ViewBag.IsAuthorizedSupplier = _suppliersHelper.IsSupplierAuthorized(UserAuth.UserId);
            ViewBag.Pager = PagerHelper.CreatePagerByUrl(page, 10, total, "");
            ViewBag.MenuMyMarketClassOver = "over";
            ViewBag.NoNeedTopAdvert = true;
            return View(data);
        }


        //申请成为创业者 视图
        public ActionResult ToBeSupplier()
        {
            ViewBag.NoNeedTopAdvert = true;
            var result = _suppliersHelper.AuthorizeSupplier(UserAuth.UserId);

            if (result.ResultType.Equals(OperationResultType.Success))
            {
                return View();
            }
            if (result.ResultType.Equals(OperationResultType.NoChanged))
            {
                return RedirectToAction("ApplyProduct");
            }
            if (result.ResultType.Equals(OperationResultType.Error) ||
                result.ResultType.Equals(OperationResultType.IllegalOperation))
            {
                ViewBag.ErrMsg = result.ResultType.ToDescription() + result.Message;
                return View();
            }
            ViewBag.MenuMyMarketClassOver = "over";

            return View();
        }

        //申请成为创业者 处理
        [HttpPost]
        public JsonResult ToBeSupplier(string linkMan, string linkTel, string reason)
        {
            var result = _suppliersHelper.AddToBeSupplier(UserAuth.UserId, linkMan, linkTel, reason);
            return ReturnHelper.Instance.GetJsonResult(result);

        }

        //产品申请、编辑  视图
        [HttpGet]
        public ActionResult ApplyProduct(int id = 0)
        {
            ViewBag.NoNeedTopAdvert = true;
            ViewBag.MenuMyMarketClassOver = "over";
            ViewBag.Categories = CategoryHelper.Instance.GetUseableCategoriesInCache().Where(f => f.IsForMarket).ToList();
            var product = _productsHelper.GetApplyEntity(id);
            return View(product);
        }

        //产品申请、编辑  处理
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult ApplyProduct(ProductsApplyEntity apply, int categoryId)
        {
            ViewBag.NoNeedTopAdvert = true;
            var result = apply.Id > 0 ? _productsHelper.ModifyProductApply(apply, UserAuth.UserId, categoryId) :
            _productsHelper.AddProductApply(apply, UserAuth.UserId, categoryId);
            if (result.ResultType.Equals(OperationResultType.Success))
            {
                return RedirectToAction("MyMarket");
            }

Msg.Web/Views/Exchanges/Index.cshtml
@model List<Msg.Bll.Models.CreditGoodsLiteModel>

@{
    ViewBag.Title = "积分兑换";
}
@section head{

    <link href="@Url.Content("~/Content/ShowLoading/showLoading.css")" rel="stylesheet" />
}
@section scripts{
    <script src="@Url.Content("~/Content/ShowLoading/jquery.showLoading.min.js")"></script>

    <script src="@Url.Content("~/Scripts/exchange.js")"></script>
}
<div class="nk_list msg_jf">
    <input type="hidden" id="currentTabId" value="1" />
    <div class="ls_list_li">
        <!--<a href="javascript:;" class="nk_qh_l"><img src="images/left.png"/></a>
        <a href="javascript:;" class="nk_qh_r"><img src="images/right.png"/></a>-->
        <ul class="clearfix">
            <li class="over" ls_list_li="0">
                <div class="tabChange li1 over" tabid="1">0-1000积分</div>
            </li>
            <li ls_list_li="1">
                <div class="tabChange li1" tabid="2">1001-3000积分</div>
            </li>
            <li ls_list_li="2">
                <div class="tabChange li1" tabid="3">3001-5000积分</div>
            </li>
            <li ls_list_li="3">
                <div class="tabChange li1" tabid="4">5001-8000积分</div>
            </li>
            <li ls_list_li="4">
                <div class="tabChange li1" tabid="5">8000积分以上</div>
            </li>
        </ul>
    </div>
    <div class="list_main" style="display: block;">
        @Html.Partial("_Index", Model)
    </div>
</div>

Msg.Web/Views/Exchanges/Item.cshtml
@using Msg.Entities
@using Msg.Utils
@using Msg.Web.App_Start
@model Msg.Entities.CreditGoodsEntity

@{
    ViewBag.Title = Model.Name + " :: 积分兑换 ";
    var comments = ViewBag.Comments as IQueryable<CommentsEntity>;
    var history = ViewBag.ViewHistory as IQueryable<GoodsEntity>;
    var hotSelling = ViewBag.HotSelling as IQueryable<GoodsEntity>;
}
@section head{

    <link href="@Url.Content("~/Content/ShowLoading/showLoading.css")" rel="stylesheet" />
}

@if (Model != null)
{

    <div class="msg_w msg_details">
        <div class="det_title"><a href="/" class="span">首页</a>&nbsp;&gt;&nbsp;<a href="@Url.Action("Index","Exchanges")">积分兑换</a>&nbsp;&gt;&nbsp;@Model.Name</div>
        <div class="det_t clearfix">
            <div class="det_img">
                <!--产品参数开始-->
                <div id="preview" class="spec-preview"> <span class="jqzoom"><img jqimg="@Model.Logo" src="@ImagesHelper.GetImgWidthHeight(Model.Logo, 350, 350, false)" alt="@Model.Name"></span> </div>

                <!--产品参数结束-->
            </div>
            <div class="det_nav">
                <div class="title">@Model.Name</div>
                <div class="wor2">
                    所需积分：<span class="span2">@Model.NeedCredits</span>
                </div>
                <div class="wor3">
                    库存数量：@(Model.Quantity) 件<br>
                    可兑次数：@(Model.ExchangeTimes) 次<br>
                    已 兑 换：@(Model.ExchangeLogs.Count) 件
                </div>
                <dl class="clearfix">
                    <dd>兑换数量：</dd>

                    <dt class="clearfix stepper" data-trigger="spinner" id="spinner">
                        <span class="dt1 calculate   down" data-spin="down">-</span>
                        <div class="dt1" style="width: 50px;">
                            <input class="stepper-input" data-rule="quantity" data-max="@Model.ExchangeTimes" min="1" id="txt_detail_buyCount" type="text" value="1">
                        </div>
                        <span class="dt1 calculate up" data-spin="up">+</span>
                    </dt>
                </dl>
                <ul class="wor4 clearfix msg_b2">
                    <li>
                        <a href="@if (Request.Url != null){@(UserAuth.IsAuthenticated ? "JavaScript:;" : Url.Action("Login", "Account", new { returnUrl = Request.Url.ToString() }))}" id="btn_exhcnage" onclick="doExchange(@Model.Id)"><img src="@Url.Content("~/Content/images/det_nav1.png")">&nbsp;立即兑换</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="msg_shop" style="margin-top: 20px;" id="div_recommendforyou">
            <ul class="shop_li clearfix">
                <li shop_li="0">为你推荐</li>
            </ul>
            <div class="shop_dp" style="display: block;" id="div_recommendforyou_container">
                <!--ajax加载-->
            </div>
        </div>
        <div class="det_main clearfix">
            <div class="main_left">
                <div class="main_l_1" id="div_hot_Selling">
                    <dl class="clearfix">
                        <dd>热门销售</dd>
                        <dt class="a2"><a href="javascript:;" id="btn_hotselling_change">换一批</a></dt>
                    </dl>
                    <div id="div_hot_Selling_container">
                        @Html.Partial("_HotSellingGoods", hotSelling)

                    </div>
                </div>
                <div class="main_l_1" style="margin-top: 20px;">
                    <dl class="clearfix">
                        <dd>最近浏览</dd>
                    </dl>
                    @Html.Partial("_HotSellingGoods", history)

                </div>
            </div>
            <div class="main_right">
                <div class="main_r_1">
                    <div class="main_r_2">商品详情&nbsp;&nbsp;<span class="cl_999999">Product details</span></div>
                    @Html.Raw(Model.Desc)
                </div>
                <div class="main_r_1" style="margin-top: 10px;">
                    <div class="main_r_2">用户评论&nbsp;&nbsp;<span class="cl_999999">User comments</span></div>
                    @if (comments != null)
                    {
                        foreach (var parent in comments)
                        {
                            <div class="main_r_3 clearfix" id="comments_@(parent.Id)">
                                <div class="r_3_l">
                                    <img src="@UserAuth.GetUsersAvatar(parent.User.Avatar)" width="70" height="70">
                                    <div class="l_wor1">@parent.User.NickName</div>
                                </div>
                                <div class="r_3_r">
                                    <div class="wor1">@parent.Content</div>
                                    <div class="wor2">
                                        @parent.CreateTime
                                        <span>&nbsp;&nbsp;|&nbsp;&nbsp;</span>
                                        <a href="javascript:;" onclick="comments.ScrollToCommentBox(@parent.Id, @parent.User.Id);return false; "><img src="@Url.Content("~/Content/images/r_3_r.png")">&nbsp;&nbsp;回复</a>
                                    </div>
                                    <div class="main_r_4">
                                        @if (parent.FollowComments != null && parent.FollowComments.Any())
                                        {
                                            foreach (var item in parent.FollowComments)
                                            {
                                                <div class="main_r_3 clearfix" id="comments_reply_@(item.Id)">
                                                    <div class="r_3_l">
                                                        <img src="@UserAuth.GetUsersAvatar(item.User.Avatar)" width="70" height="70">
                                                        <div class="l_wor1">@item.User.NickName</div>
                                                    </div>
                                                    <div class="r_3_r">
                                                        <div class="wor1">
                                                            <b>回复@(item.BeReplyedUser.NickName):</b>&nbsp;@item.Content
                                                        </div>
                                                        <div class="wor2">
                                                            @item.CreateTime
                                                            <span>&nbsp;&nbsp;|&nbsp;&nbsp;</span>
                                                            <a href="javascript:;" onclick="comments.ScrollToCommentBox(@item.Id, @item.User.Id);return false; "><img src="@Url.Content("~/Content/images/r_3_r.png")">&nbsp;&nbsp;回复</a>
                                                        </div>
                                                    </div>
                                                </div>
                                            }
                                        }

                                    </div>
                                </div>
                            </div>
                        }

                    }

                </div>
                @Html.Raw(ViewBag.Pager)
                <div class="main_r_1" style="margin-top: 10px;" id="div_comment_reply">
                    <input type="hidden" id="h_replyTo" value="0" />
                    <input type="hidden" id="h_pageNo" value="@ViewBag.PageNum" />
                    <input type="hidden" id="h_beReplyedUserId" value="0" />
                    <input type="hidden" id="h_goodsId" value="@Model.Id" />
                    <div class="main_r_2">评论&nbsp;&nbsp;<span class="cl_999999">Comment</span></div>
                    <div class="main_t">
                        <textarea name="" id="txt_comment_content" cols="" rows=""></textarea>
                    </div>
                    <div class="main_a clearfix">
                        @if (UserAuth.IsAuthenticated)
                        {
                            <a href="javascript:;" onclick=" comments.AddComment();return false; ">发表评论</a>
                        }
                        else
                        {
                            <a href="@Url.Action("Login", "Account", new {returnUrl = Request.Url.ToString()})">发表评论</a>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

    @section scripts{
        <script src="@Url.Content("~/Content/ShowLoading/jquery.showLoading.min.js")"></script>
        <script src="@Url.Content("~/Scripts/jquery.spinner.min.js")"></script>
        <script src="@Url.Content("~/Scripts/exchange.js")"></script>
        <script type="text/javascript">
            var hotSellingPage = 1;
            var maxExchangeTimes = @(Model.ExchangeTimes);
            var quantity = @(Model.Quantity);

            var goodsId = @(Model.Id);
            $(function () {
               
                //数量增减
                $('[data-trigger="spinner"]').spinner('delay', 100).spinner('changed', function (e, newVal, oldVal) {
                    //trigger lazed, depend on delay option.

                });
                //为你推荐
                $("#div_recommendforyou").showLoading();
                $.get("@Url.Action("_RecommendForyouGoods","Home")", {}, function (data) {
                    $("#div_recommendforyou_container").html(data);
                    $("#div_recommendforyou").hideLoading();
                });
                //热销 换一批
                $("#btn_hotselling_change").bind("click", function () {
                    $("#div_hot_Selling").showLoading();
                    var pageNoStr = $("#h_hotSelling_page").val();
                    if (isEmpty(pageNoStr)) {
                        pageNoStr = "1";
                    }
                    var pageNum = parseInt(pageNoStr);
                    if (!isNaN(pageNum)) {
                        $.get("@Url.Action("_HotSellingGoods", "Home")", { page: pageNum + 1 }, function (data) {
                            $("#div_hot_Selling_container").html(data);
                            $("#div_hot_Selling").hideLoading();
                        });
                    }
                });
            });
        </script>
    }
}

Msg.Web/Views/Exchanges/_Index.cshtml
@using Msg.Utils
@model System.Collections.Generic.List<Msg.Bll.Models.CreditGoodsLiteModel>

<ul class="clearfix">
    @if (Model != null && Model.Any())
    {
        foreach (var item in Model)
        {
            <li>
                <div class="li_img">
                    <a href="@Url.Action("Item", new { id = item.Id })" target="_blank"><img class="lazy" src="@ImagesHelper.GetImgWidthHeight(item.Logo, 220, 220, false)" width="220" height="220"></a>
                </div>
                <div class="li1">@(item.NeedCredits)积分</div>
                <div class="li2">
                    <a href="@Url.Action("Item", new { id = item.Id })" target="_blank">@item.Name</a>
                </div>
                <div class="li4">
                    <a href="@Url.Action("Item", new { id = item.Id })" target="_blank">立即兑换</a>
                </div>
            </li>
        }
    }


</ul>
<div class="msg_f" style="padding: 20px 0;">@Html.Raw(ViewBag.Pager)</div>

Msg.Web/Views/Exchanges/_MyAddress.cshtml
@model System.Linq.IQueryable<Msg.Entities.UserAddressEntity>

<div class="msg_fill2">
    <div class="fill2_1 a2">
        收货人信息&nbsp;&nbsp;<a href="@Url.Action("MyAddresses", "Me")">[修改/添加]</a>
    </div>
    @if (Model != null && Model.Any())
    {
        foreach (var item in Model)
        {
            <input name="rd_exchange_address" type="radio" value="@item.Id" @(item.IsDefult ? "checked='checked'" : "")><div class="fill2_2 a2">@item.ReciverName&nbsp;&nbsp;&nbsp;@item.DetailAddress&nbsp;&nbsp;&nbsp;@item.ReciverTel</div>
        }
    }
    <input type="hidden" id="h_address_Count" value="@(Model==null?0:Model.Count())" />
</div>